# permissions for end users to view podtatoservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtatoserver-viewer-role
rules:
- apiGroups:
  - helloservice-demo.helloservice
  resources:
  - podtatoservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helloservice-demo.helloservice
  resources:
  - podtatoservers/status
  verbs:
  - get
