# permissions for end users to edit podtatoservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtatoserver-editor-role
rules:
- apiGroups:
  - helloservice-demo.helloservice
  resources:
  - podtatoservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helloservice-demo.helloservice
  resources:
  - podtatoservers/status
  verbs:
  - get
