apiVersion: v1
kind: Service
metadata:
  name: helloservice
  namespace: demospace
spec:
  type: ClusterIP
  selector:
    app: helloservice-rollout
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer